# coding: utf-8

"""
    lnbits

    API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.  # noqa: E501

    The version of the OpenAPI document: 0.10.9
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.http_validation_error import HTTPValidationError
from openapi_client import configuration


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
