# coding: utf-8

"""
    lnbits

    API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.  # noqa: E501

    The version of the OpenAPI document: 0.10.9
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.admin_api_v1_settings_.delete import ApiDeleteSettingsAdminApiV1SettingsDelete
from openapi_client.paths.admin_api_v1_backup_.get import ApiDownloadBackupAdminApiV1BackupGet
from openapi_client.paths.api_v1_conversion.post import ApiFiatAsSatsApiV1ConversionPost
from openapi_client.paths.admin_api_v1_settings_.get import ApiGetSettingsAdminApiV1SettingsGet
from openapi_client.paths.api_v1_extension.post import ApiInstallExtensionApiV1ExtensionPost
from openapi_client.paths.api_v1_currencies.get import ApiListCurrenciesAvailableApiV1CurrenciesGet
from openapi_client.paths.api_v1_lnurlscan_code.get import ApiLnurlscanApiV1LnurlscanCodeGet
from openapi_client.paths.api_v1_payments_payment_hash.get import ApiPaymentApiV1PaymentsPaymentHashGet
from openapi_client.paths.api_v1_payments.post import ApiPaymentsCreateApiV1PaymentsPost
from openapi_client.paths.api_v1_payments_decode.post import ApiPaymentsDecodeApiV1PaymentsDecodePost
from openapi_client.paths.api_v1_payments_lnurl.post import ApiPaymentsPayLnurlApiV1PaymentsLnurlPost
from openapi_client.paths.api_v1_payments_sse.get import ApiPaymentsSseApiV1PaymentsSseGet
from openapi_client.paths.api_v1_lnurlauth.post import ApiPerformLnurlauthApiV1LnurlauthPost
from openapi_client.paths.public_v1_payment_payment_hash.get import ApiPublicPaymentLongpollingPublicV1PaymentPaymentHashGet
from openapi_client.paths.admin_api_v1_restart_.get import ApiRestartServerAdminApiV1RestartGet
from openapi_client.paths.api_v1_extension_ext_id.delete import ApiUninstallExtensionApiV1ExtensionExtIdDelete
from openapi_client.paths.admin_api_v1_settings_.put import ApiUpdateSettingsAdminApiV1SettingsPut
from openapi_client.paths.api_v1_wallet_new_name.put import ApiUpdateWalletApiV1WalletNewNamePut
from openapi_client.paths.api_v1_wallet.get import ApiWalletApiV1WalletGet
from openapi_client.paths.admin_api_v1_audit.get import AuditAdminApiV1AuditGet
from openapi_client.paths.api_v1_extension_ext_id_db.delete import DeleteExtensionDbApiV1ExtensionExtIdDbDelete
from openapi_client.paths.api_v1_extension_release_org_repo_tag_name.get import GetExtensionReleaseApiV1ExtensionReleaseOrgRepoTagNameGet
from openapi_client.paths.api_v1_extension_ext_id_releases.get import GetExtensionReleasesApiV1ExtensionExtIdReleasesGet
from openapi_client.paths.api_v1_health.get import HealthApiV1HealthGet
from openapi_client.paths.api_v1_qrcode_data.get import ImgApiV1QrcodeDataGet
from openapi_client.paths.api_v1_payments.get import PaymentListApiV1PaymentsGet
from openapi_client.paths.api_v1_payments_paginated.get import PaymentListApiV1PaymentsPaginatedGet
from openapi_client.paths.api_v1_tinyurl.post import TinyurlApiV1TinyurlPost
from openapi_client.paths.api_v1_tinyurl_tinyurl_id.delete import TinyurlApiV1TinyurlTinyurlIdDelete
from openapi_client.paths.api_v1_tinyurl_tinyurl_id.get import TinyurlApiV1TinyurlTinyurlIdGet
from openapi_client.paths.t_tinyurl_id.get import TinyurlTTinyurlIdGet
from openapi_client.paths.admin_api_v1_topup_.put import TopupAdminApiV1TopupPut
from openapi_client.paths.api_v1_ws_item_id_data.get import WebsocketUpdateGetApiV1WsItemIdDataGet
from openapi_client.paths.api_v1_ws_item_id.post import WebsocketUpdatePostApiV1WsItemIdPost


class CoreApi(
    ApiDeleteSettingsAdminApiV1SettingsDelete,
    ApiDownloadBackupAdminApiV1BackupGet,
    ApiFiatAsSatsApiV1ConversionPost,
    ApiGetSettingsAdminApiV1SettingsGet,
    ApiInstallExtensionApiV1ExtensionPost,
    ApiListCurrenciesAvailableApiV1CurrenciesGet,
    ApiLnurlscanApiV1LnurlscanCodeGet,
    ApiPaymentApiV1PaymentsPaymentHashGet,
    ApiPaymentsCreateApiV1PaymentsPost,
    ApiPaymentsDecodeApiV1PaymentsDecodePost,
    ApiPaymentsPayLnurlApiV1PaymentsLnurlPost,
    ApiPaymentsSseApiV1PaymentsSseGet,
    ApiPerformLnurlauthApiV1LnurlauthPost,
    ApiPublicPaymentLongpollingPublicV1PaymentPaymentHashGet,
    ApiRestartServerAdminApiV1RestartGet,
    ApiUninstallExtensionApiV1ExtensionExtIdDelete,
    ApiUpdateSettingsAdminApiV1SettingsPut,
    ApiUpdateWalletApiV1WalletNewNamePut,
    ApiWalletApiV1WalletGet,
    AuditAdminApiV1AuditGet,
    DeleteExtensionDbApiV1ExtensionExtIdDbDelete,
    GetExtensionReleaseApiV1ExtensionReleaseOrgRepoTagNameGet,
    GetExtensionReleasesApiV1ExtensionExtIdReleasesGet,
    HealthApiV1HealthGet,
    ImgApiV1QrcodeDataGet,
    PaymentListApiV1PaymentsGet,
    PaymentListApiV1PaymentsPaginatedGet,
    TinyurlApiV1TinyurlPost,
    TinyurlApiV1TinyurlTinyurlIdDelete,
    TinyurlApiV1TinyurlTinyurlIdGet,
    TinyurlTTinyurlIdGet,
    TopupAdminApiV1TopupPut,
    WebsocketUpdateGetApiV1WsItemIdDataGet,
    WebsocketUpdatePostApiV1WsItemIdPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
